### ISSUE TITLE
Move release announcements to e-editiones homepage

### ISSUE THREAD

**Issue by joewiz** [eeditiones/e-editiones-website#11]
All release announcements from https://teipublisher.com/exist/apps/tei-publisher/doc/blog/ should be moved to e-editiones with proper tags (tei-publisher, announcement, release).

**Comment by joewiz** [comment]
@wolfgangmm I began looking into this tonight and have set up a conversion pipeline for the old blog posts to the new website, e.g., from a source page like https://teipublisher.com/exist/apps/tei-publisher/doc/blog/tei-publisher-40.xml I can generate [tei-publisher-4.md](https://github.com/eeditiones/e-editiones-website/files/10915892/tei-publisher-4.md) pretty easily (sending [the API output](https://teipublisher.com/exist/apps/tei-publisher/api/parts/doc%2Fblog%2Ftei-publisher-40.xml/json?user.skipAuthors=true&user.language=en-US&odd=docbook.odd&view=single) through pandoc's HTML-to-commonmark conversion), with the manual work mostly limited to the YAML header block. 

The only thing I don't think I can do is customize the image. Is it ok if I just use the existing image from the tei-publisher-lib-3 article, as in my sample linked above?

Do you have any preference about keeping the slugs in the original format (tei-publisher-40) vs the newer style (tei-publisher-4)? 

Also, do the old articles in tei-publisher-app need to come down? Do we have any sort of redirect facility for sending people who might request an old article over to its new location.

Please let me know if you had any other thoughts about the migration.

**Comment by joewiz** [comment]
p.s. I hope I created this issue in the right repository. If it should be in the planning repo, I can definitely move it there.

**Comment by wolfgangmm** [comment]
Thanks a lot @joewiz, this looks good. Transforming the slugs is ok. And I would indeed take down the old blog functionality in tei-publisher-app. The "News" link in the menu should then point to e-editiones posts tagged as "release". This way, even people having bookmarked the old link have a way to figure out where to go.

As for the image, you could also leave the `coverImage` and `coverImageCredits` empty. A default image will be used automatically in this case.

**Comment by JoernT** [comment]
@wolfgangmm you talk about changing the publisher homepage right? that should point to https://www.e-editiones.org/tags/release/ then?

Am i right that this is the last thing to do for this ticket?

**Comment by tuurma** [comment]
@joern Wolfgang spoke about the tei-publisher-app, already taken care of.  But you're correct that also teipublisher.com needs repointing the links.

@joewiz Brilliant work on migrating the data and your thoughtful improvements, we appreciate it greatly.

**Comment by joewiz** [comment]
@tuurma Thanks for reviewing! Happy to help!
